### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ghost** [Tschrock/PM-PMTranslator#1]
translate
15:32:07 [INFO] Usage: /translate (From Language) to <To Language> <Text to be translated>
translate Korean Russian Test
15:32:22 [INFO] [PMTranslator] Could not translate text
translate English Test
15:32:32 [INFO] [PMTranslator] Could not translate text
translate English Korean test
15:32:39 [INFO] [PMTranslator] Could not translate text
translate test
15:32:44 [INFO] [PMTranslator] Could not translate text
translate 구글
15:32:48 [INFO] [PMTranslator] Could not translate text
translate 안녕
15:34:02 [INFO] [PMTranslator] Could not translate text
translate fu
15:34:07 [INFO] [PMTranslator] Could not translate text

First, sorry. How to use? T.T

**Comment by StarProgamGamer** [comment]
i dunno
